<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \OaiPmhHarvester\Form\HarvestForm $form
 */

$translate = $this->plugin('translate');
?>

<?= $this->pageTitle($translate('Set repository to harvest'), 1, $translate('OAI-PMH Harvester')) ?>

<?= $this->form()->openTag($form) ?>
<fieldset id='page-actions'>
    <button type="submit"><?= $translate('View sets') ?></button>
</fieldset>
<?= $this->formCollection($form, false) ?>

<?= $this->form()->closeTag($form) ?>
