<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \OaiPmhHarvester\Api\Representation\HarvestRepresentation[] $harvests
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$hyperlink = $this->plugin('hyperlink');
$url = $this->plugin('url');

$this->htmlElement('body')->appendAttribute('class', 'oaipmhharvester jobs harvests undo');
?>

<?= $this->pageTitle($translate('Past Imports'), 1, $translate('OAI-PMH Harvester')) ?>
<?php if (empty($harvests)): ?>

<?= $translate('There are no harvests currently.') ?>

<?php else: ?>
<?= $this->pagination() ?>

<form method='POST'>
    <fieldset id='page-actions'>
        <input type="submit" value="<?= $escape($translate('Submit')) ?>" />
    </fieldset>
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?= $escape($translate('Undo?')) ?></th>
                <th><?= $escape($translate('Date')) ?></th>
                <th><?= $escape($translate('Label')) ?></th>
                <th><?= $escape($translate('Comment')) ?></th>
                <th><?= $escape($translate('Results')) ?></th>
                <th><?= $escape($translate('Status')) ?></th>
                <th><?= $escape($translate('Owner')) ?></th>
            </tr>
        </thead>
        <tbody>

        <?php foreach ($harvests as $harvest): ?>
        <?php $job = $harvest->job(); ?>
        <?php $undoJob = $harvest->undoJob(); ?>
        <?php $setSpec = $harvest->getSetSpec(); ?>
        <?php $setName = $harvest->getSetName(); ?>
        <tr class="<?= $undoJob ? 'undone' : '' ?>">
            <td>
                <input type="checkbox" name="jobs[]" value="<?= $job->id() ?>" <?= $undoJob ? ' disabled="disabled"' : '' ?>/>
            </td>
            <td>
                <span class="oai-pmh-date">
                    <?= $escape($this->i18n()->dateFormat($job->started())) ?>
                </span>
                <br/>
                <span class="oai-pmh-job">
                    <?= $job->link($translate('Job details')) ?>
                </span>
                <?php if ($job->log()): ?>
                /
                <span class="oai-pmh-log">
                    <?= $job->link($translate('Log'), 'log', ['target' => '_blank']) ?>
                </span>
                <?php endif; ?>
            </td>
            <td>
                <?php $setName = $harvest->getSetName(); ?>
                <?php $setSpec = $harvest->getSetSpec(); ?>
                <?php if (!$setName || $setName === $setSpec): ?>
                [<span class="oai-pmh-set"><?= $escape($setSpec) ?></span>]
                <?php else: ?>
                <span class="oai-pmh-set"><?= $escape($setName) ?></span>
                    <?php if ($setSpec): ?>
                [<span class="oai-pmh-set"><?= $escape($setSpec) ?></span>]
                    <?php endif; ?>
                <?php endif; ?>
            </td>
            <td>
                <?= $translate($harvest->comment()) ?>
                <?php if ($harvest->hasErr()): ?>
                    <p><?= $translate('Problems were detected with the import. Check the job’s log for details.') ?></p>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($stats = $harvest->stats()): ?>
                <?php foreach ($stats as $statKey => $statValue): ?>
                <span class="oai-pmh-stat">
                    <?= sprintf($translate('%s: %s'), $translate($statKey), $statValue) ?>
                </span>
                <br/>
                <?php endforeach; ?>
                <?php else: ?>
                <?= sprintf($translate('Imported: %d %s'), $harvest->totalImported(), $translate('items'/* $harvest->resourceType() */)) ?>
                <?php endif; ?>
            </td>
            <td>
                <?php
                if ($undoJob):
                    if ($undoJob->ended()):
                        echo $translate('Undone') . ' ' . $escape($this->i18n()->dateFormat($undoJob->ended()));
                    else:
                        echo $translate('Undo in progress');
                    endif;
                    ?>
                    <span class="oai-pmh-job">
                        <?= $undoJob->link($translate('Job details')) ?>
                    </span>
                    <?php if ($undoJob->log()): ?>
                    /
                    <span class="oai-pmh-log">
                        <?= $undoJob->link($translate('Log'), 'log', ['target' => '_blank']) ?>
                    </span>
                    <?php
                    endif;
                else:
                    echo $escape($translate($job->status()));
                endif;
                ?>
            </td>
            <td>
                <?= $hyperlink($job->owner()->name(), $url('admin/id', ['controller' => 'user', 'action' => 'show', 'id' => $job->owner()->id()])) ?>
            </td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</form>
<?php endif; ?>
