<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \OaiPmhHarvester\Form\SetsForm $form
 * @var string $repositoryName
 * @var int|null $total
 */

$translate = $this->plugin('translate');

$sets = $form->getOption('sets');
?>

<?= $this->pageTitle($translate('Select sets to import'), 1, $translate('OAI-PMH Harvester')) ?>
<h2><?= $repositoryName ?></h2>
<p>
    <?= sprintf($translate('This repository has %d sets.'), $total) ?>
    <?php if ($total > count($sets)): ?>
    <?= sprintf($translate('Only the first %d are displayed.'), count($sets)) ?>
    <?php endif; ?>
</p>
<p>
    <?= $translate('Please choose a set to import.') ?>
</p>

<?= $this->form()->openTag($form) ?>
<fieldset id="page-actions">
    <button type="submit"><?= $translate('Harvest') ?></button>
</fieldset>
<?= $this->formCollection($form, false) ?>
<?= $this->form()->closeTag($form) ?>
