<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \OaiPmhHarvester\Api\Representation\HarvestJobRepresentation[] $imports
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'oaipmhharvester harvests undo');
?>

<?php echo $this->pageTitle($translate('Past Imports'), 1, $translate('OAI-PMH Harvester')); ?>
<?php if(empty($imports)): ?>

<?php else: ?>
<?php echo $this->pagination(); ?>

<form method='POST'>
    <fieldset id='page-actions'>
        <input type="submit" value="<?php echo $escape($translate('Submit')); ?>" />
    </fieldset>
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?php echo $escape($translate('Undo?'));?></th>
                <th><?php echo $this->sortLink($translate('Job ID'), 'id');?></th>
                <th><?php echo $escape($translate('Comment'));?></th>
                <th><?php echo $escape($translate('Imported content'));?></th>
                <th><?php echo $escape($translate('Date'));?></th>
                <th><?php echo $escape($translate('Status'));?></th>
                <th><?php echo $escape($translate('Owner'));?></th>
            </tr>
        </thead>
        <tbody>

        <?php foreach ($imports as $import): ?>
        <?php $job = $import->job(); ?>
        <?php $undoJob = $import->undoJob(); ?>
        <tr class="<?php echo $undoJob ? 'undone' : ''; ?>" >
            <td>
                <input type='checkbox' name='jobs[]' value='<?php echo $job->id(); ?>' />
            </td>
            <td><?php echo $job->link($job->id()); ?></td>
            <td class='comment'>
                <?php echo $import->comment(); ?>
                <?php if($import->hasErr()): ?>
                    <p><?php echo $translate("Problems were detected with the import. Check the job's log for details."); ?></p>
                <?php endif; ?>
            </td>
            <td>
                <?php //echo $translate('Added: ') . $import->addedCount() . ' ' . $translate($import->resourceType()); ?>
            </td>
            <td><?php echo $escape($this->i18n()->dateFormat($job->started())); ?></td>
            <td>
            <?php if ($undoJob) {
                if ($undoJob->ended()) {
                    $status = $translate('Undone') . ' ' . $escape($this->i18n()->dateFormat($undoJob->ended()));
                } else {
                    $status = $translate('Undo in progress');
                }
            } else {
                $status = $translate($job->status());
            }
            ?>
            <?php echo $status; ?>
            </td>
            <td><?php echo $this->hyperlink($job->owner()->name(), $this->url('admin/id', array('controller' => 'user', 'action' => 'show', 'id' => $job->owner()->id()))); ?></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</form>
<?php endif; ?>
